  
name: Publish post from issue

on:
  issues:
    types: ['labeled']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate Post
        env:
          POST_TITLE: ${{ github.event.issue.title }}
          POST_BODY: ${{ github.event.issue.body }}
          CREATED_AT: ${{ github.event.issue.created_at }}
        run: |
          # echo "$POST_TITLE - $CREATED_AT"
          YEAR=$(date -d "$CREATED_AT" '+%Y')
          # echo $YEAR
          # echo $POST_BODY        
          save_to="content/posts/$YEAR/$POST_TITLE"
          mkdir -p "$save_to"
          cd "$save_to"
        
          echo "---" > index.md
          echo "title: $POST_TITLE" >> index.md
          echo "date: $(date -d "$CREATED_AT" '+%Y-%m-%d')" >> index.md
          echo "tags: [${{ join(github.event.issue.labels.*.name, ', ') }}]" >> index.md
          echo "---" >> index.md
          
          echo "" >> index.md
          echo $POST_BODY >> index.md
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          delete-branch: true
          title: "publish: ${{ github.event.issue.title}}"
          body: |
            Automagically sprouted for publishing.
            Merging will publish to: https://shazow.net/posts/${{ github.event.issue.title }}
            Closes #${{ github.event.issue.number }}
          reviewers: "${{ github.repository_owner }}"
          commit-message: "post: ${{ github.event.issue.title }}"
